import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import './button-groups.scss';
import './buttons.scss';
import './close.scss';
import './code.scss';
import './dropdowns.scss';
import './forms:scss';
import './glyphicons.scss';
import './grid.scss';
import './jumbotron.scss';
import './media.scss';
import './mixins.scss';
import './modals.scss';
import './navbar.scss';
import './navs.scss';
import './normalize.scss';
import './pagination.scss';
import './responsive-embed.scss';
import './tables.scss';
import './themes.scss';
import './variables.scss';
import './style.scss';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
