import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import './_bootstrap-compass.scss';
import './_alerts.scss';
import './_badges-scss';
import './_breadcrumbs.scss';
import App from './App';
import './_button-groups.scss';
import './_buttons.scss';
import './_close.scss';
import './_code.scss';
import './_dropdowns.scss';
import './_forms:scss';
import './_glyphicons.scss';
import './_grid.scss';
import './_jumbotron.scss';
import './_media.scss';
import './_mixins.scss';
import './_modals.scss';
import './_navbar.scss';
import './_navs.scss';
import './_normalize.scss';
import './_pagination.scss';
import './_responsive-embed.scss';
import './_tables.scss';
import './_themes.scss';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
